name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Pack NuGet Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Package
        run: dotnet build -c Release

      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: src/FakeHttpMessageHandler/FakeHttpMessageHandler.csproj # Specify your .csproj file path

      - name: Pack NuGet Package
        run: dotnet pack -c Release --no-build --output ./artifacts /p:Version=${{ steps.package_version.outputs.version }}

  test:
    name: Test NuGet Package
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test

  deploy:
    name: Deploy NuGet Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Publish NuGet Package
        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} 

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Create Release Branch
        run: |
          git checkout -b release/${{ steps.get_version.outputs.version }}

      - name: Add NuGet version tag
        run: |
          git tag -a ${{ steps.get_version.outputs.version }} -m "NuGet version: ${{ steps.get_version.outputs.version }}"

      - name: Push branch and tag
        run: |
          git push origin release/${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.version, 'prev') }}
          body: |
            Release for version ${{ steps.get_version.outputs.version }}